parameters:
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/*'
    exclude:
      - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
      - '../src/Infrastructure/Doctrine/Migrations'
  App\Domains\Account\Controller\:
    resource: '../src/Domains/Account/Controller'
    tags: ['controller.service_arguments']
  App\Domains\Project\Controller\:
    resource: '../src/Domains/Project/Controller'
    tags: ['controller.service_arguments']
  App\Infrastructure\Doctrine\EventListener\HashPasswordListener:
    tags:
      - { name: doctrine.orm.entity_listener, lazy: true }