parameters:
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/*'
    exclude:
      - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
      - '../src/Infrastructure/Doctrine/Migrations'

  App\Domains\Project\Controller\:
    resource: '../src/Domains/Project/Controller'
    tags: ['controller.service_arguments']

imports:
  - { resource: '../src/Domains/Account/Resource/config/services.yaml' }